[package]
name = "scratch_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.94", features = ["span-locations"] }
quote = "1.0.39"
syn = { version = "2.0.99", features = ["extra-traits"] }
